### ISSUE TITLE
Phoenix 1.4.0 Released! 🎉 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#118]
https://phoenixframework.org/blog/phoenix-1-4-0-released 🚀 
If you are using Phoenix for _any_ project (_personal or work_) this is a _must_ read!

HN thread: https://news.ycombinator.com/item?id=18402634 💬 
(good buzz from wider web dev community)

Also, Phoenix LiveView is going to be _game-changing_! 🦄 https://twitter.com/chris_mccord/status/1059273315666350080
+ [x] Watch Chris’ Elixir Conf keynote: https://youtu.be/Z2DU0qLfPIY

# Todo
Update the following Phoenix Examples to 1.4:
+ [x] Chat: https://github.com/dwyl/phoenix-chat-example > see: [#12](https://github.com/dwyl/phoenix-chat-example/pull/12) and [#13](https://github.com/dwyl/phoenix-chat-example/pull/13) (code changes required)
+ [x] Encryption: https://github.com/dwyl/phoenix-ecto-encryption-example 
+ [x] Append-only: https://github.com/dwyl/phoenix-ecto-append-only-log-example

There shouldn't be much to change/update, we just need to run through each example using 1.4 and _confirm_ that everything still works as expected.

**Comment by nelsonic** [comment]
@SimonLab yesterday you mentioned that you were considering looking at the encryption and append-only log examples to refresh your Phoenix knowledge (_after having done 4 months on a Node.js project_) 🙄 

Please pick one of those and go through it using Phoenix 1.4.
Please make any necessary updates to the guide to make it 1.4-compatible.
I have done this for the Chat example: https://github.com/dwyl/phoenix-chat-example/pull/12
only a handful of updates were required.

**Comment by nelsonic** [comment]
Meanwhile _most_ of our Apps have been upgraded/updated to Phoenix `1.6` e.g: https://github.com/dwyl/phoenix-chat-example/pull/62 🚀 
Closing this. ✅
