### ISSUE TITLE
Phoenix v1.6.0 Released! 🚀

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#143]
_Really_ excited about this release: https://github.com/phoenixframework/phoenix/tags
<img width="952" alt="phoenix-1 6rc" src="https://user-images.githubusercontent.com/194400/132956828-a51c6da6-c456-4398-9cf5-2b69c8a7ad39.png">

While this may appear to be a "minor" update (from SemVer perspective), it's actually pretty significant.
See: CHANGELOG: [https://github.com/phoenixframework/phoenix/blob/master/CHANGELOG.md#changelog-for-v16](https://github.com/phoenixframework/phoenix/blob/8d1fa447c21c7a607be95d540360d64bf5aba173/CHANGELOG.md#changelog-for-v16)

# Todo

+ [x] Try `1.6` on a smaller project: https://github.com/dwyl/elixir-auth-github-demo/pull/18
  + [x] Then try it on a bigger project: https://github.com/dwyl/phoenix-chat-example/issues/55
+ [x] Investigate email using https://github.com/swoosh/swoosh > `GOTO`: https://github.com/dwyl/email/issues/52
+ [x] Look into `mix phx.gen.auth` generator https://github.com/dwyl/auth/issues/133 (_this is **great** news!_)

**Comment by nelsonic** [comment]
https://www.phoenixframework.org/blog/phoenix-1.6-released

**Comment by nelsonic** [comment]
<img width="1045" alt="phoenix-1 6-released" src="https://user-images.githubusercontent.com/194400/134863644-2dd7763a-de2f-43a3-a235-3285c20dc013.png">

# 🚀

**Comment by nelsonic** [comment]
```
$ mix archive.install hex phx_new
Resolving Hex dependencies...
Dependency resolution completed:
New:
  phx_new 1.6.0
* Getting phx_new (Hex package)
All dependencies are up to date
Compiling 11 files (.ex)
Generated phx_new app
Generated archive "phx_new-1.6.0.ez" with MIX_ENV=prod
Found existing entry: ~/.mix/archives/phx_new-1.5.5
Are you sure you want to replace it with "phx_new-1.6.0.ez"? [Yn] y
* creating ~/.mix/archives/phx_new-1.6.0
```

**Comment by nelsonic** [comment]
Full list of `deps` for a brand new Phoenix `1.6` app:
```elixir
  defp deps do
    [
      {:phoenix, "~> 1.6.0"},
      {:phoenix_ecto, "~> 4.4"},
      {:ecto_sql, "~> 3.6"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.16.0"},
      {:floki, ">= 0.30.0", only: :test},
      {:phoenix_live_dashboard, "~> 0.5"},
      {:esbuild, "~> 0.2", runtime: Mix.env() == :dev},
      {:swoosh, "~> 1.3"},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:gettext, "~> 0.18"},
      {:jason, "~> 1.2"},
      {:plug_cowboy, "~> 2.5"}
    ]
  end
```

**Comment by nelsonic** [comment]
Building static assets and hot-reloading is _sooooo_ much faster!!

```
22:00:46.776 [debug] Downloading esbuild from https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.12.18.tgz

  ../priv/static/assets/app.css  9.6kb
  ../priv/static/assets/app.js   1.3kb

⚡ Done in 10ms
==> app
```

**Comment by nelsonic** [comment]
Updated the Hits app https://hits.dwyl.com to use Phoenix `1.6.2` https://github.com/dwyl/hits/pull/128

**Comment by nelsonic** [comment]
We now have a "real" Phoenix `1.6.2` App in "***Production***"! 🎉 
Closing this ticket as _confident_ Phoenix 1.6 is working for us. ✅

**Comment by nelsonic** [comment]
`GOTO` #152
